// Query name: taxi_analysis_2024. ProjectRoot is a text parameter containing the extracted folder path.
let
    Source = Csv.Document(File.Contents(ProjectRoot & "/data/processed/taxi_analysis_2024_final.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    EmptyToNull = Table.TransformColumns(Headers, {{"PULocationID", each if _ = "" then null else _, type nullable text},{"airport_trip_share", each if _ = "" then null else _, type nullable text},{"trip_count", each if _ = "" then null else _, type nullable text},{"total_revenue", each if _ = "" then null else _, type nullable text},{"total_fare_amount", each if _ = "" then null else _, type nullable text},{"total_tip_amount", each if _ = "" then null else _, type nullable text},{"total_trip_distance", each if _ = "" then null else _, type nullable text},{"total_trip_duration_min", each if _ = "" then null else _, type nullable text},{"tipped_trip_count", each if _ = "" then null else _, type nullable text},{"card_trip_count", each if _ = "" then null else _, type nullable text},{"cash_trip_count", each if _ = "" then null else _, type nullable text},{"flex_fare_trip_count", each if _ = "" then null else _, type nullable text},{"airport_fee_missing_count", each if _ = "" then null else _, type nullable text},{"tip_missing_count", each if _ = "" then null else _, type nullable text},{"airport_pickup", each if _ = "" then null else _, type nullable text},{"elapsed_hours", each if _ = "" then null else _, type nullable text},{"dst_ambiguous", each if _ = "" then null else _, type nullable text},{"pickup_month", each if _ = "" then null else _, type nullable text},{"pickup_dayofweek", each if _ = "" then null else _, type nullable text},{"pickup_hour_num", each if _ = "" then null else _, type nullable text},{"is_weekend", each if _ = "" then null else _, type nullable text},{"hour_segment_order", each if _ = "" then null else _, type nullable text},{"rain_mm", each if _ = "" then null else _, type nullable text},{"trace_precipitation", each if _ = "" then null else _, type nullable text},{"precipitation_known", each if _ = "" then null else _, type nullable text},{"temp_c", each if _ = "" then null else _, type nullable text},{"visibility", each if _ = "" then null else _, type nullable text},{"wind_speed", each if _ = "" then null else _, type nullable text},{"rain_flag", each if _ = "" then null else _, type nullable text},{"moderate_rain_flag", each if _ = "" then null else _, type nullable text},{"heavy_rain_flag", each if _ = "" then null else _, type nullable text},{"low_visibility_flag", each if _ = "" then null else _, type nullable text},{"is_dark", each if _ = "" then null else _, type nullable text},{"avg_total_amount", each if _ = "" then null else _, type nullable text},{"avg_fare_amount", each if _ = "" then null else _, type nullable text},{"avg_tip_amount", each if _ = "" then null else _, type nullable text},{"avg_trip_distance", each if _ = "" then null else _, type nullable text},{"avg_trip_duration_min", each if _ = "" then null else _, type nullable text},{"tip_rate", each if _ = "" then null else _, type nullable text},{"cash_trip_share", each if _ = "" then null else _, type nullable text},{"card_trip_share", each if _ = "" then null else _, type nullable text},{"flex_fare_share", each if _ = "" then null else _, type nullable text}}),
    Typed = Table.TransformColumnTypes(EmptyToNull, {{"pickup_hour", type datetime},
        {"PULocationID", Int64.Type},
        {"airport_trip_share", Int64.Type},
        {"trip_count", Int64.Type},
        {"total_revenue", type number},
        {"total_fare_amount", type number},
        {"total_tip_amount", type number},
        {"total_trip_distance", type number},
        {"total_trip_duration_min", type number},
        {"tipped_trip_count", Int64.Type},
        {"card_trip_count", Int64.Type},
        {"cash_trip_count", Int64.Type},
        {"flex_fare_trip_count", Int64.Type},
        {"airport_fee_missing_count", Int64.Type},
        {"tip_missing_count", Int64.Type},
        {"pickup_borough", type text},
        {"pickup_zone", type text},
        {"pickup_service_zone", type text},
        {"pickup_borough_clean", type text},
        {"pickup_borough_grouped", type text},
        {"airport_pickup", Int64.Type},
        {"elapsed_hours", Int64.Type},
        {"dst_ambiguous", Int64.Type},
        {"pickup_month", Int64.Type},
        {"pickup_dayofweek", Int64.Type},
        {"pickup_hour_num", Int64.Type},
        {"is_weekend", Int64.Type},
        {"pickup_weekday_name", type text},
        {"hour_segment_order", Int64.Type},
        {"hour_segment", type text},
        {"rain_mm", type number},
        {"trace_precipitation", type number},
        {"precipitation_known", Int64.Type},
        {"temp_c", type number},
        {"visibility", type number},
        {"wind_speed", type number},
        {"precipitation_category", type text},
        {"rain_flag", Int64.Type},
        {"moderate_rain_flag", Int64.Type},
        {"heavy_rain_flag", Int64.Type},
        {"low_visibility_flag", Int64.Type},
        {"temp_bin", type text},
        {"is_dark", Int64.Type},
        {"avg_total_amount", type number},
        {"avg_fare_amount", type number},
        {"avg_tip_amount", type number},
        {"avg_trip_distance", type number},
        {"avg_trip_duration_min", type number},
        {"tip_rate", type number},
        {"cash_trip_share", type number},
        {"card_trip_share", type number},
        {"flex_fare_share", type number}}, "en-US")
in
    Typed
